---
driver:
  name: ec2
  region: us-east-1
  availability_zone: c
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  security_group_ids:
    - <%= ENV['AWS_SG']  %>
  associate_public_ip: true
  interface: dns
  instance_type: t3.micro
  retryable_tries: 180
  tags:
    Name: "amimoto-die-hard"

transport:
  username: ec2-user
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']  %>
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

provisioner:
  name: shell

platforms:
  - name: hvm-amimoto
    driver:
      image_id: ami-06dcd90ae27b13ace # 6.4
  - name: modphp-amimoto
    driver:
      image_id: ami-0ce707520e7584280 # 6.4
  - name: woo-hvm-amimoto
    driver:
      image_id: ami-0794cbbdbb990e140 # 6.4
  - name: woo-modphp-amimoto
    driver:
      image_id: ami-0e87d5f6934111e69 # 6.4

verifier:
  name: shell
  command: bundle exec rspec -fd spec/2019/
#  sleep: 300

suites:
  - name: default
    run_list:
    attributes:
<%
## Periodic outputs for CircleCI
if ENV['CI']
  ppid = Process.pid
  Process.fork {
    loop {
      puts "."
      begin
        Process.getpgid( ppid )
        sleep 20
      rescue
        exit 0
      end
    }
  }
end
%>
